# Generated by Django 2.2.7 on 2020-08-22 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('number', models.IntegerField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrive_go', models.CharField(max_length=255)),
                ('depart_go', models.CharField(max_length=255)),
                ('arrive_come', models.CharField(max_length=255)),
                ('depart_come', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('line_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Line')),
            ],
        ),
    ]
