# Generated by Django 2.2.7 on 2020-08-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_time_station_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='arrive_come',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='time',
            name='arrive_go',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='time',
            name='depart_come',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='time',
            name='depart_go',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
